// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsH9DedVCIHgQL8lLkSJVI9FeIEiQ9UN0',
    appId: '1:152430852946:web:54c035bb2c6f341f26188b',
    messagingSenderId: '152430852946',
    projectId: 'foodapp-f7fde',
    authDomain: 'foodapp-f7fde.firebaseapp.com',
    storageBucket: 'foodapp-f7fde.appspot.com',
    measurementId: 'G-VP9MY5DB3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNiwKAirbGxbGO0ChPGKRCe9DxJcCvJ7s',
    appId: '1:152430852946:android:1619398a041c288226188b',
    messagingSenderId: '152430852946',
    projectId: 'foodapp-f7fde',
    storageBucket: 'foodapp-f7fde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACziE7EIe0_mh7NimBNhSYcQi7GUSw2Xk',
    appId: '1:152430852946:ios:608e5b9174454e9026188b',
    messagingSenderId: '152430852946',
    projectId: 'foodapp-f7fde',
    storageBucket: 'foodapp-f7fde.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACziE7EIe0_mh7NimBNhSYcQi7GUSw2Xk',
    appId: '1:152430852946:ios:608e5b9174454e9026188b',
    messagingSenderId: '152430852946',
    projectId: 'foodapp-f7fde',
    storageBucket: 'foodapp-f7fde.appspot.com',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsH9DedVCIHgQL8lLkSJVI9FeIEiQ9UN0',
    appId: '1:152430852946:web:303f175f20e025f826188b',
    messagingSenderId: '152430852946',
    projectId: 'foodapp-f7fde',
    authDomain: 'foodapp-f7fde.firebaseapp.com',
    storageBucket: 'foodapp-f7fde.appspot.com',
    measurementId: 'G-01LBMF109R',
  );
}
